### ISSUE TITLE
Provide python wrapper

### ISSUE THREAD

**Issue by karlheinzkurt** [karlheinzkurt/ticket-decoder#1]

**Comment by botkero** [comment]
any updates? Im kinda interested but I dont know much about c++ to get started here. So python would be great.

I wanna scan my ticket to transfer it to an NFC tag (is that possible?)

**Comment by karlheinzkurt** [comment]
until now, no updates. honestly i thought someone would write a wrapper and would create a pull request. 

but i like the idea since it would make it accessible to much wieder range of people. i did a quick check what options of python wrappers are there in 2024. i'm writing that explicit since i remember i was using swig in 2004 to wrap c++ to python in a project, hehe almost 20 years ago :-) anyway, since boost is a dependency already, we could try to use boost::python to get it managed, i guess this is the best option to avoid even more dependencies.
but i have to think about, what methods are useful to have available. because it does not make sense to have opencv inside the wrapped component and in python (much easier to access) as well. so in a first run i would check out the technical boost::python stuff and would try to provide one method to convert base64 encoded uic918-content into json (aztec-code decoding into base64 raw bytes containing #UT... would be in python world). when this should work quite easy, then i would think about a reasonable api-design.

related to nfc: when you decoded the ticket data into json, i guess, it should be possible transfer this information via nfc or any other communication method/protocol. anyway, without any concrete use-case, it hard to tell if this ticket-decoder lib is fitting there.

**Comment by botkero** [comment]
> related to nfc: when you decoded the ticket data into json, i guess, it should be possible transfer this information via nfc or any other communication method/protocol. anyway, without any concrete use-case, it hard to tell if this ticket-decoder lib is fitting there.

Does this mean that I have my data in the NFC tag, but cannot use it during controls?
I may have misunderstood something.

**Comment by karlheinzkurt** [comment]
sorry, i don't understand your question. this library does nothing with NFC and it is up to you, to do whatever you want with decoded information from aztec-codes read from images/pdfs or camera. this library or related applications just make it possible to see/access the information from aztec-codes used for ticketing.
